"""empty message

Revision ID: d660aa60b5d7
Revises: 
Create Date: 2021-05-28 12:44:10.610419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd660aa60b5d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trained',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_pkl', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trained')
    op.drop_table('paper')
    op.drop_table('author')
    # ### end Alembic commands ###
